import type { Offre, Trip } from './types'

const now = new Date()
const in6h = new Date(now.getTime() + 6 * 60 * 60 * 1000).toISOString()
const in24h = new Date(now.getTime() + 24 * 60 * 60 * 1000).toISOString()

export const MOCK_OFFRES: Offre[] = [
  {
    id: '1',
    commerce: {
      id: 'c1',
      nom: 'Chez Lévesque Bistro',
      adresse: '4297 rue Saint-Denis',
      quartier: 'Plateau-Mont-Royal',
      latitude: 45.5231,
      longitude: -73.5827,
      photo_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
      categories: ['resto'],
    },
    titre: "Menu table d'hôte complet",
    description: 'Entrée + plat + dessert. Cuisine du marché, produits locaux québécois.',
    categorie: 'resto',
    prix_normal: 38,
    prix_flash: 22,
    reduction_pct: 42,
    code_promo: 'FLASH22',
    places_disponibles: 8,
    expire_at: in6h,
    created_at: now.toISOString(),
    est_active: true,
  },
  {
    id: '2',
    commerce: {
      id: 'c2',
      nom: 'La Sala Rossa',
      adresse: '4848 boul. Saint-Laurent',
      quartier: 'Mile-End',
      latitude: 45.5258,
      longitude: -73.5941,
      photo_url: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800',
      categories: ['show'],
    },
    titre: 'Soirée jazz fusion — Le Collectif Nomade',
    description: 'Jazz fusion en salle intime, 200 personnes max.',
    categorie: 'show',
    prix_normal: 35,
    prix_flash: 18,
    reduction_pct: 49,
    code_promo: 'JAZZ18',
    places_disponibles: 15,
    expire_at: in24h,
    created_at: now.toISOString(),
    est_active: true,
  },
  {
    id: '3',
    commerce: {
      id: 'c3',
      nom: "Zone d'Aventure Escape",
      adresse: '2340 rue Beaubien Est',
      quartier: 'Rosemont',
      latitude: 45.5401,
      longitude: -73.5742,
      photo_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
      categories: ['activite'],
    },
    titre: 'Escape game 60 min — groupe de 2 à 6',
    description: '3 salles disponibles, niveaux facile à difficile.',
    categorie: 'activite',
    prix_normal: 30,
    prix_flash: 17,
    reduction_pct: 43,
    code_promo: 'ESCAPE17',
    places_disponibles: 6,
    expire_at: in24h,
    created_at: now.toISOString(),
    est_active: true,
  },
]

export const MOCK_TRIPS: Trip[] = [
  {
    id: 't1',
    ville_depart: 'Montréal',
    destination: 'Mont-Tremblant',
    date_depart: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    heure_depart: '8h00',
    lieu_depart: 'Métro Montmorency',
    places_total: 4,
    places_restantes: 3,
    prix_par_personne: 15,
    organisateur_id: 'u1',
    description: "Weekend ski + détente. Partage des frais d'essence.",
    type: 'aller_retour',
    created_at: now.toISOString(),
  },
  {
    id: 't2',
    ville_depart: 'Montréal',
    destination: 'Québec City',
    date_depart: new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    heure_depart: '9h00',
    lieu_depart: 'Métro Berri-UQAM',
    places_total: 5,
    places_restantes: 2,
    prix_par_personne: 20,
    organisateur_id: 'u2',
    description: 'Visite du Vieux-Québec. Retour le soir même.',
    type: 'aller_simple',
    created_at: now.toISOString(),
  },
  {
    id: 't3',
    ville_depart: 'Montréal',
    destination: 'Ottawa',
    date_depart: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    heure_depart: '7h30',
    lieu_depart: 'Métro McGill',
    places_total: 3,
    places_restantes: 1,
    prix_par_personne: 25,
    organisateur_id: 'u3',
    description: 'Trajet régulier chaque vendredi matin.',
    type: 'recurrent',
    created_at: now.toISOString(),
  },
]
